name: Block Invalid PRs (Staging ↔ Main)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-pr-path:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source and target branches
        run: |
          # Block staging ↔ main PRs
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" == "staging" ]] || 
             [[ "${{ github.base_ref }}" == "staging" && "${{ github.head_ref }}" == "main" ]]; then
            echo "::error::Direct PRs between 'staging' and 'main' are not allowed. Use 'development' as an intermediate branch."
            exit 1
          fi
